// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTIC.Infrastructure.Data;

#nullable disable

namespace WebApiTIC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiTIC.Domain.Entities.Asignaciones", b =>
                {
                    b.Property<int>("AsignacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignacionId"));

                    b.Property<int>("EmpleadosId")
                        .HasColumnType("int");

                    b.Property<int>("EquiposId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.HasKey("AsignacionId");

                    b.HasIndex("EmpleadosId");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("WebApiTIC.Domain.Entities.Empleados", b =>
                {
                    b.Property<int>("EmpleadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadosId"));

                    b.Property<string>("Cedula_Pasaporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadosId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("WebApiTIC.Domain.Entities.Equipos", b =>
                {
                    b.Property<int>("EquiposId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquiposId"));

                    b.Property<string>("Almacenamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AsignacionesAsignacionId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadosId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Memoria_Ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Equipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procesador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquiposId");

                    b.HasIndex("AsignacionesAsignacionId");

                    b.HasIndex("EmpleadosId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("WebApiTIC.Domain.Entities.Asignaciones", b =>
                {
                    b.HasOne("WebApiTIC.Domain.Entities.Empleados", "Empleados")
                        .WithMany()
                        .HasForeignKey("EmpleadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("WebApiTIC.Domain.Entities.Equipos", b =>
                {
                    b.HasOne("WebApiTIC.Domain.Entities.Asignaciones", null)
                        .WithMany("Equipos")
                        .HasForeignKey("AsignacionesAsignacionId");

                    b.HasOne("WebApiTIC.Domain.Entities.Empleados", "Empleados")
                        .WithMany("Equipos")
                        .HasForeignKey("EmpleadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("WebApiTIC.Domain.Entities.Asignaciones", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("WebApiTIC.Domain.Entities.Empleados", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
